// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-vibes/EditorialBroadsheet.tsx": () => import("../components/mockups/homepage-vibes/EditorialBroadsheet.tsx"),
  "./components/mockups/homepage-vibes/ObsidianPrestige.tsx": () => import("../components/mockups/homepage-vibes/ObsidianPrestige.tsx"),
  "./components/mockups/homepage-vibes/WarmAntiquarian.tsx": () => import("../components/mockups/homepage-vibes/WarmAntiquarian.tsx")
};
